# Generated by Django 5.2 on 2025-04-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_pinstyle_treefamily_treegenus_treespecies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endemictree',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='app.location'),
        ),
    ]
