# Generated by Django 5.2 on 2025-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_endemictree_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='endemictree',
            name='health_status',
            field=models.CharField(choices=[('very_poor', 'Very Poor'), ('poor', 'Poor'), ('good', 'Good'), ('very_good', 'Very Good'), ('excellent', 'Excellent')], default='good', max_length=20),
        ),
    ]
