# Generated by Django 5.2.1 on 2025-05-13 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_endemictree_health_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='treefamily',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treegenus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treespecies',
            name='scientific_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='endemictree',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='endemictree',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endemic_trees', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='location',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='pinstyle',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_styles', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='treefamily',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_families', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='treegenus',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_genera', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='treespecies',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_species', to='app.workspace'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='app.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='endemictree',
            unique_together={('species', 'location', 'year', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='maplayer',
            unique_together={('name', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='pinstyle',
            unique_together={('name', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='treefamily',
            unique_together={('name', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='treegenus',
            unique_together={('name', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='treespecies',
            unique_together={('scientific_name', 'workspace')},
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together={('key', 'workspace')},
        ),
    ]
