# Generated by Django 5.2.1 on 2025-05-15 02:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_treefamily_name_alter_treegenus_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='workspace',
        ),
        migrations.AlterUniqueTogether(
            name='maplayer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pinstyle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treefamily',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treegenus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treespecies',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='endemictree',
            unique_together={('species', 'location', 'year')},
        ),
        migrations.AlterField(
            model_name='treefamily',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='treegenus',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='treespecies',
            name='scientific_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='pinstyle',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='treefamily',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='treegenus',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='treespecies',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='endemictree',
            name='workspace',
        ),
        migrations.CreateModel(
            name='TreeSeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(help_text='Number of seeds planted')),
                ('planting_date', models.DateField(default=django.utils.timezone.now)),
                ('germination_status', models.CharField(choices=[('not_germinated', 'Not Germinated'), ('germinating', 'Germinating'), ('partially_germinated', 'Partially Germinated'), ('fully_germinated', 'Fully Germinated'), ('failed', 'Failed to Germinate')], default='not_germinated', max_length=20)),
                ('germination_date', models.DateField(blank=True, help_text='Date when germination was first observed', null=True)),
                ('survival_rate', models.FloatField(blank=True, help_text='Percentage of seeds that survived (0-100)', null=True)),
                ('expected_maturity_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='app.location')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='app.treespecies')),
            ],
            options={
                'ordering': ['-planting_date'],
                'indexes': [models.Index(fields=['planting_date'], name='app_treesee_plantin_e03717_idx')],
            },
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
