# Generated by Django 5.2.1 on 2025-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_location_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treespecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='species/'),
        ),
    ]
