# Generated by Django 5.2.1 on 2025-10-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_treespecies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='endemictree',
            name='bad_count',
            field=models.IntegerField(default=0, help_text='Number of trees in poor/very poor condition'),
        ),
        migrations.AddField(
            model_name='endemictree',
            name='deceased_count',
            field=models.IntegerField(default=0, help_text='Number of deceased trees'),
        ),
        migrations.AddField(
            model_name='endemictree',
            name='good_count',
            field=models.IntegerField(default=0, help_text='Number of trees in good condition'),
        ),
        migrations.AddField(
            model_name='endemictree',
            name='healthy_count',
            field=models.IntegerField(default=0, help_text='Number of healthy trees (excellent/very good)'),
        ),
    ]
