# Generated by Django 5.2.1 on 2025-10-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_endemictree_bad_count_endemictree_deceased_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endemictree',
            name='bad_count',
            field=models.IntegerField(default=0, help_text='Number of trees in poor/very poor health'),
        ),
        migrations.AlterField(
            model_name='endemictree',
            name='good_count',
            field=models.IntegerField(default=0, help_text='Number of trees in good health'),
        ),
        migrations.AlterField(
            model_name='endemictree',
            name='healthy_count',
            field=models.IntegerField(default=0, help_text='Number of trees in excellent/very good health'),
        ),
    ]
