# Generated by Django 5.2 on 2025-11-20 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_endemictree_bad_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endemictree',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='endemictree',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endemic_trees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maplayer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pinstyle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_styles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treefamily',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treegenus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_genera', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treeseed',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_seeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treespecies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tree_species', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='treefamily',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treegenus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treespecies',
            name='scientific_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='endemictree',
            unique_together={('user', 'species', 'location', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('user', 'latitude', 'longitude')},
        ),
        migrations.AlterUniqueTogether(
            name='maplayer',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='pinstyle',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='treefamily',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='treegenus',
            unique_together={('user', 'name', 'family')},
        ),
        migrations.AlterUniqueTogether(
            name='treespecies',
            unique_together={('user', 'scientific_name')},
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together={('user', 'key')},
        ),
        migrations.AddIndex(
            model_name='endemictree',
            index=models.Index(fields=['user'], name='app_endemic_user_id_fba4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='treeseed',
            index=models.Index(fields=['user'], name='app_treesee_user_id_b0a5fc_idx'),
        ),
    ]
