# Generated by Django 4.2.26 on 2025-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_user_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='endemictree',
            name='app_endemic_user_id_fba4bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='treeseed',
            name='app_treesee_user_id_b0a5fc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='maplayer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pinstyle',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treefamily',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treegenus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treespecies',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='treeseed',
            name='user',
        ),
        migrations.AlterField(
            model_name='treefamily',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='treegenus',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='treespecies',
            name='scientific_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='endemictree',
            unique_together={('species', 'location', 'year')},
        ),
        migrations.RemoveField(
            model_name='endemictree',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maplayer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pinstyle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='treefamily',
            name='user',
        ),
        migrations.RemoveField(
            model_name='treegenus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='treespecies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersetting',
            name='user',
        ),
    ]
