# Generated by Django 4.2.25 on 2025-11-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_endemictree_app_endemic_user_id_fba4bc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for this location (shared by all trees at this location)', null=True, upload_to='locations/'),
        ),
    ]
