# Generated by Django 4.2.25 on 2025-11-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_location_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
        migrations.AddField(
            model_name='endemictree',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for this tree species at this location (shared by all trees with same location, common_name, and scientific_name)', null=True, upload_to='trees/'),
        ),
    ]
