# Generated by Django 4.2.25 on 2025-11-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_location_image_endemictree_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='endemictree',
            name='hectares',
            field=models.FloatField(blank=True, help_text='Area covered in hectares', null=True),
        ),
        migrations.AddField(
            model_name='treeseed',
            name='hectares',
            field=models.FloatField(blank=True, help_text='Area covered in hectares', null=True),
        ),
    ]
