# Generated by Django 4.2.25 on 2025-11-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_endemictree_hectares_treeseed_hectares'),
    ]

    operations = [
        # Set default value for any null hectares
        migrations.RunSQL(
            "UPDATE app_endemictree SET hectares = 0.0 WHERE hectares IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE app_treeseed SET hectares = 0.0 WHERE hectares IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Make hectares non-nullable
        migrations.AlterField(
            model_name='endemictree',
            name='hectares',
            field=models.FloatField(help_text='Area covered in hectares'),
        ),
        migrations.AlterField(
            model_name='treeseed',
            name='hectares',
            field=models.FloatField(help_text='Area covered in hectares'),
        ),
    ]
