# Generated by Django 4.2.26 on 2025-11-27 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_endemictree_user_location_user_maplayer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treefamily',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treegenus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treespecies',
            name='scientific_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='treefamily',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='treegenus',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='treespecies',
            unique_together={('scientific_name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='usersetting',
            unique_together={('key', 'user')},
        ),
    ]
