# Generated by Django 4.2.26 on 2025-12-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='endemictree',
            name='image_format',
            field=models.CharField(blank=True, choices=[('JPEG', 'JPEG'), ('PNG', 'PNG')], help_text='Format of the uploaded image', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='treespecies',
            name='image_format',
            field=models.CharField(blank=True, choices=[('JPEG', 'JPEG'), ('PNG', 'PNG')], help_text='Format of the uploaded image', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='endemictree',
            name='image',
            field=models.BinaryField(blank=True, help_text='Image for this tree species stored as binary data (shared by all trees with same common_name and scientific_name)', null=True),
        ),
        migrations.AlterField(
            model_name='treespecies',
            name='image',
            field=models.BinaryField(blank=True, help_text='Tree image stored as binary data', null=True),
        ),
    ]
