# Generated by Django 4.2.26 on 2025-12-01 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_change_image_to_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endemictree',
            name='image_format',
        ),
        migrations.RemoveField(
            model_name='treespecies',
            name='image_format',
        ),
        migrations.AlterField(
            model_name='endemictree',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for this tree species at this location (shared by all trees with same location, common_name, and scientific_name)', null=True, upload_to='trees/'),
        ),
        migrations.AlterField(
            model_name='treespecies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='species/'),
        ),
        migrations.CreateModel(
            name='TreeSpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('image_data', models.BinaryField(help_text='Image stored as BYTEA in PostgreSQL')),
                ('content_type', models.CharField(default='image/jpeg', help_text='MIME type of the image', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tree Species Images',
                'unique_together': {('common_name', 'scientific_name', 'user')},
            },
        ),
    ]
