# Generated by Django 4.2.26 on 2025-12-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_change_species_image_to_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='geojson_data',
            field=models.JSONField(blank=True, help_text='GeoJSON data stored as JSONB', null=True),
        ),
        migrations.AlterField(
            model_name='maplayer',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
