# Generated by Django 5.2 on 2025-12-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_geojson_data_to_maplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='endemictree',
            name='is_healthy',
            field=models.BooleanField(default=True, help_text='Whether the tree is healthy (True) or not healthy (False)'),
        ),
        migrations.AddField(
            model_name='endemictree',
            name='is_planted',
            field=models.BooleanField(default=False, help_text='Whether the tree is planted (True) or existing (False)'),
        ),
    ]

