# Generated by Django 5.2 on 2025-12-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_endemictree_is_healthy_is_planted'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True, help_text='Human-readable address from reverse geocoding', null=True),
        ),
    ]

