# Generated by Django 4.2.26 on 2026-01-15 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0027_remove_endemictree_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplayer',
            name='geojson_data',
        ),
        migrations.AlterField(
            model_name='endemictree',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('app_user', 'App User'), ('public_user', 'Public User')], default='app_user', max_length=20),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('csv_upload', 'CSV Upload'), ('manual_entry', 'Manual Tree Entry'), ('delete_tree', 'Delete Tree'), ('delete_trees_bulk', 'Bulk Delete Trees'), ('delete_all_trees', 'Delete All Trees')], max_length=50)),
                ('description', models.TextField(help_text='Description of the action')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'History Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
