# Generated by Django 4.2.26 on 2026-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_maplayer_geojson_data_alter_endemictree_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('csv_upload', 'CSV Upload'), ('manual_entry', 'Manual Tree Entry'), ('edit_tree', 'Edit Tree'), ('delete_tree', 'Delete Tree'), ('delete_trees_bulk', 'Bulk Delete Trees'), ('delete_all_trees', 'Delete All Trees')], max_length=50),
        ),
    ]
