# Generated by Django 4.2.26 on 2025-11-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreePhotoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_description', models.TextField(help_text='Description of the endemic tree')),
                ('latitude', models.FloatField(help_text='Latitude coordinate')),
                ('longitude', models.FloatField(help_text='Longitude coordinate')),
                ('person_name', models.CharField(help_text='Name of the person submitting', max_length=200)),
                ('tree_image', models.BinaryField(help_text='Tree image stored as binary data')),
                ('image_format', models.CharField(choices=[('JPEG', 'JPEG'), ('PNG', 'PNG')], help_text='Format of the uploaded image', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tree Photo Submission',
                'verbose_name_plural': 'Tree Photo Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
